(* generated by dune *)

(** @canonical Shexp_bigstring_io.Bigstring *)
module Bigstring = Shexp_bigstring_io__Bigstring

(** @canonical Shexp_bigstring_io.Std *)
module Std = Shexp_bigstring_io__Std
