(* generated by dune *)

(** @canonical Ppx_stable.Abstract *)
module Abstract = Ppx_stable__Abstract

(** @canonical Ppx_stable.Ast_helpers *)
module Ast_helpers = Ppx_stable__Ast_helpers

(** @canonical Ppx_stable.Generic_map *)
module Generic_map = Ppx_stable__Generic_map

(** @canonical Ppx_stable.Invariants *)
module Invariants = Ppx_stable__Invariants

(** @canonical Ppx_stable.Naming *)
module Naming = Ppx_stable__Naming

(** @canonical Ppx_stable.Record *)
module Record = Ppx_stable__Record

(** @canonical Ppx_stable.Variants *)
module Variants = Ppx_stable__Variants

module Ppx_stable__ = struct end
[@@deprecated "this module is shadowed"]
