(* generated by dune *)

(** @canonical Ppx_log_types.Import *)
module Import = Ppx_log_types__Import

(** @canonical Ppx_log_types.Jsonaf *)
module Jsonaf = Ppx_log_types__Jsonaf

(** @canonical Ppx_log_types.Level *)
module Level = Ppx_log_types__Level

(** @canonical Ppx_log_types.Log_tag *)
module Log_tag = Ppx_log_types__Log_tag

(** @canonical Ppx_log_types.Message_data *)
module Message_data = Ppx_log_types__Message_data

(** @canonical Ppx_log_types.Message_sexp *)
module Message_sexp = Ppx_log_types__Message_sexp

(** @canonical Ppx_log_types.Message_source *)
module Message_source = Ppx_log_types__Message_source

(** @canonical Ppx_log_types.Tag_data *)
module Tag_data = Ppx_log_types__Tag_data

module Ppx_log_types__ = struct end
[@@deprecated "this module is shadowed"]
