(* generated by dune *)

(** @canonical Octavius.Common *)
module Common = Octavius__Common

(** @canonical Octavius.Errors *)
module Errors = Octavius__Errors

(** @canonical Octavius.OctLexer *)
module OctLexer = Octavius__OctLexer

(** @canonical Octavius.OctParser *)
module OctParser = Octavius__OctParser

(** @canonical Octavius.Print *)
module Print = Octavius__Print

(** @canonical Octavius.Types *)
module Types = Octavius__Types
