(* generated by dune *)

(** @canonical Shexp_process.Debugger_intf *)
module Debugger_intf = Shexp_process__Debugger_intf

(** @canonical Shexp_process.Debuggers *)
module Debuggers = Shexp_process__Debuggers

(** @canonical Shexp_process.Env *)
module Env = Shexp_process__Env

(** @canonical Shexp_process.Exit_status *)
module Exit_status = Shexp_process__Exit_status

(** @canonical Shexp_process.Import *)
module Import = Shexp_process__Import

(** @canonical Shexp_process.Job *)
module Job = Shexp_process__Job

(** @canonical Shexp_process.Prim *)
module Prim = Shexp_process__Prim

(** @canonical Shexp_process.Process *)
module Process = Shexp_process__Process

(** @canonical Shexp_process.Signal *)
module Signal = Shexp_process__Signal

(** @canonical Shexp_process.Std *)
module Std = Shexp_process__Std

(** @canonical Shexp_process.Std_io *)
module Std_io = Shexp_process__Std_io

module Shexp_process__ = struct end
[@@deprecated "this module is shadowed"]
