(* generated by dune *)

(** @canonical Linux_ext.Epoll *)
module Epoll = Linux_ext__Epoll

(** @canonical Linux_ext.Epoll_intf *)
module Epoll_intf = Linux_ext__Epoll_intf

(** @canonical Linux_ext.Linux_ext_intf *)
module Linux_ext_intf = Linux_ext__Linux_ext_intf

module Linux_ext__ = struct end
[@@deprecated "this module is shadowed"]
