(* generated by dune *)

(** @canonical Expect_test_helpers_base.Expect_test_helpers_base_intf *)
module Expect_test_helpers_base_intf = Expect_test_helpers_base__Expect_test_helpers_base_intf

module Expect_test_helpers_base__ = struct end
[@@deprecated "this module is shadowed"]
