(* generated by dune *)

(** @canonical Time_ns_unix.Time_ns_unix_intf *)
module Time_ns_unix_intf = Time_ns_unix__Time_ns_unix_intf

module Time_ns_unix__ = struct end
[@@deprecated "this module is shadowed"]
