(* generated by dune *)

(** @canonical Hash_heap.Hash_heap_intf *)
module Hash_heap_intf = Hash_heap__Hash_heap_intf

(** @canonical Hash_heap.Import *)
module Import = Hash_heap__Import

module Hash_heap__ = struct end
[@@deprecated "this module is shadowed"]
