(* generated by dune *)

(** @canonical Sexp_pretty.Config *)
module Config = Sexp_pretty__Config

(** @canonical Sexp_pretty.Sexp_pretty_intf *)
module Sexp_pretty_intf = Sexp_pretty__Sexp_pretty_intf

module Sexp_pretty__ = struct end
[@@deprecated "this module is shadowed"]
