(* generated by dune *)

(** @canonical Ppx_custom_printf.Format_lifter *)
module Format_lifter = Ppx_custom_printf__Format_lifter

module Ppx_custom_printf__ = struct end
[@@deprecated "this module is shadowed"]
