(* generated by dune *)

(** @canonical Tuple_pool.Import *)
module Import = Tuple_pool__Import

(** @canonical Tuple_pool.Tuple_pool_intf *)
module Tuple_pool_intf = Tuple_pool__Tuple_pool_intf

(** @canonical Tuple_pool.Tuple_type *)
module Tuple_type = Tuple_pool__Tuple_type

(** @canonical Tuple_pool.Tuple_type_intf *)
module Tuple_type_intf = Tuple_pool__Tuple_type_intf

module Tuple_pool__ = struct end
[@@deprecated "this module is shadowed"]
