(* generated by dune *)

(** @canonical Posixat.Posixat_generated *)
module Posixat_generated = Posixat__Posixat_generated

(** @canonical Posixat.Types *)
module Types = Posixat__Types

module Posixat__ = struct end
[@@deprecated "this module is shadowed"]
