(* generated by dune *)

(** @canonical Command_test_helpers.Import *)
module Import = Command_test_helpers__Import

module Command_test_helpers__ = struct end
[@@deprecated "this module is shadowed"]
