(* generated by dune *)

(** @canonical Yocaml_syndication_test.Atom_test *)
module Atom_test = Yocaml_syndication_test__Atom_test

(** @canonical Yocaml_syndication_test.Opml_test *)
module Opml_test = Yocaml_syndication_test__Opml_test

(** @canonical Yocaml_syndication_test.Rss1_test *)
module Rss1_test = Yocaml_syndication_test__Rss1_test

(** @canonical Yocaml_syndication_test.Rss2_test *)
module Rss2_test = Yocaml_syndication_test__Rss2_test

(** @canonical Yocaml_syndication_test.Test_util *)
module Test_util = Yocaml_syndication_test__Test_util

(** @canonical Yocaml_syndication_test.Xml_test *)
module Xml_test = Yocaml_syndication_test__Xml_test
