opam-version: "2.0"
lib: [
  "_build/install/default/lib/ppx_string_conv/META"
  "_build/install/default/lib/ppx_string_conv/dune-package"
  "_build/install/default/lib/ppx_string_conv/opam"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.a"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.cma"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.cmi"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.cmt"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.cmti"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.cmx"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.cmxa"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.ml"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.mli"
]
doc: [
  "_build/install/default/doc/ppx_string_conv/LICENSE.md"
  "_build/install/default/doc/ppx_string_conv/README.md"
]
libexec: [
  "_build/install/default/lib/ppx_string_conv/ppx.exe"
  "_build/install/default/lib/ppx_string_conv/ppx_string_conv.cmxs"
]
