(* generated by dune *)

(** @canonical Core_unix.File_descr *)
module File_descr = Core_unix__File_descr

(** @canonical Core_unix.Import *)
module Import = Core_unix__Import

(** @canonical Core_unix.Syscall_result *)
module Syscall_result = Core_unix__Syscall_result

(** @canonical Core_unix.Syscall_result_intf *)
module Syscall_result_intf = Core_unix__Syscall_result_intf

(** @canonical Core_unix.Unix_error *)
module Unix_error = Core_unix__Unix_error

module Core_unix__ = struct end
[@@deprecated "this module is shadowed"]
