#ifndef CORE_CONFIG_EXT_H
#define CORE_CONFIG_EXT_H
#define JSC_UNIX_PTY
#endif
#ifndef CONFIG_H_CONFIG_H
#define CONFIG_H_CONFIG_H
#undef  JSC_ARCH_BIG_ENDIAN
#define JSC_ARCH_SIXTYFOUR
#undef  JSC_CLOCK_GETCPUCLOCKID
#undef  JSC_EVENTFD
#define JSC_FDATASYNC
#undef  JSC_LINUX_EXT
#undef  JSC_MEMFD
#undef  JSC_MKOSTEMP
#define JSC_MSG_NOSIGNAL
#define JSC_POSIX_TIMERS
#undef  JSC_PTHREAD_NP
#define JSC_READDIR_DTYPE
#undef  JSC_RECVMMSG
#define JSC_RLIMIT_AS
#undef  JSC_RLIMIT_NICE
#define JSC_SO_NOSIGPIPE
#undef  JSC_THREAD_CPUTIME
#define JSC_THREAD_ID_METHOD (1)
#undef  JSC_TIMERFD
#define JSC_TIMESPEC
#define JSC_WORDEXP
#endif
