(* generated by dune *)

(** @canonical Yocaml_syndication.Atom *)
module Atom = Yocaml_syndication__Atom

(** @canonical Yocaml_syndication.Category *)
module Category = Yocaml_syndication__Category

(** @canonical Yocaml_syndication.Datetime *)
module Datetime = Yocaml_syndication__Datetime

(** @canonical Yocaml_syndication.Generator *)
module Generator = Yocaml_syndication__Generator

(** @canonical Yocaml_syndication.Lang *)
module Lang = Yocaml_syndication__Lang

(** @canonical Yocaml_syndication.Media_type *)
module Media_type = Yocaml_syndication__Media_type

(** @canonical Yocaml_syndication.Opml *)
module Opml = Yocaml_syndication__Opml

(** @canonical Yocaml_syndication.Person *)
module Person = Yocaml_syndication__Person

(** @canonical Yocaml_syndication.Rss1 *)
module Rss1 = Yocaml_syndication__Rss1

(** @canonical Yocaml_syndication.Rss2 *)
module Rss2 = Yocaml_syndication__Rss2

(** @canonical Yocaml_syndication.Text_input *)
module Text_input = Yocaml_syndication__Text_input

(** @canonical Yocaml_syndication.Tz *)
module Tz = Yocaml_syndication__Tz

(** @canonical Yocaml_syndication.Xml *)
module Xml = Yocaml_syndication__Xml

module Yocaml_syndication__ = struct end
[@@deprecated "this module is shadowed"]
