(* generated by dune *)

(** @canonical Expect_test_helpers_core.Expect_test_helpers_core_intf *)
module Expect_test_helpers_core_intf = Expect_test_helpers_core__Expect_test_helpers_core_intf

module Expect_test_helpers_core__ = struct end
[@@deprecated "this module is shadowed"]
