(* generated by dune *)

(** @canonical Diffable_cinaps.Tuple_helpers *)
module Tuple_helpers = Diffable_cinaps__Tuple_helpers

module Diffable_cinaps__ = struct end
[@@deprecated "this module is shadowed"]
