(* generated by dune *)

(** @canonical Interval_unix.Interval_unix_intf *)
module Interval_unix_intf = Interval_unix__Interval_unix_intf

module Interval_unix__ = struct end
[@@deprecated "this module is shadowed"]
