(* generated by dune *)

(** @canonical Diffable.Atomic *)
module Atomic = Diffable__Atomic

(** @canonical Diffable.Basic_diffs *)
module Basic_diffs = Diffable__Basic_diffs

(** @canonical Diffable.Diff_intf *)
module Diff_intf = Diffable__Diff_intf

(** @canonical Diffable.Diffable_intf *)
module Diffable_intf = Diffable__Diffable_intf

(** @canonical Diffable.Map_diff *)
module Map_diff = Diffable__Map_diff

(** @canonical Diffable.Of_variant *)
module Of_variant = Diffable__Of_variant

(** @canonical Diffable.Optional_diff *)
module Optional_diff = Diffable__Optional_diff

(** @canonical Diffable.Set_diff *)
module Set_diff = Diffable__Set_diff

(** @canonical Diffable.Tuples *)
module Tuples = Diffable__Tuples

module Diffable__ = struct end
[@@deprecated "this module is shadowed"]
