(* generated by dune *)

(** @canonical Yocaml_expect_test.Slug_test *)
module Slug_test = Yocaml_expect_test__Slug_test

(** @canonical Yocaml_expect_test.Toc_test *)
module Toc_test = Yocaml_expect_test__Toc_test
