(* generated by dune *)

(** @canonical Time_float_unix.Import *)
module Import = Time_float_unix__Import

(** @canonical Time_float_unix.Time_functor *)
module Time_functor = Time_float_unix__Time_functor

(** @canonical Time_float_unix.Time_functor_intf *)
module Time_functor_intf = Time_float_unix__Time_functor_intf

module Time_float_unix__ = struct end
[@@deprecated "this module is shadowed"]
