(* generated by dune *)

(** @canonical Yocaml.Action *)
module Action = Yocaml__Action

(** @canonical Yocaml.Archetype *)
module Archetype = Yocaml__Archetype

(** @canonical Yocaml.Cache *)
module Cache = Yocaml__Cache

(** @canonical Yocaml.Cmd *)
module Cmd = Yocaml__Cmd

(** @canonical Yocaml.Data *)
module Data = Yocaml__Data

(** @canonical Yocaml.Deps *)
module Deps = Yocaml__Deps

(** @canonical Yocaml.Diagnostic *)
module Diagnostic = Yocaml__Diagnostic

(** @canonical Yocaml.Eff *)
module Eff = Yocaml__Eff

(** @canonical Yocaml.Lexicon *)
module Lexicon = Yocaml__Lexicon

(** @canonical Yocaml.Make *)
module Make = Yocaml__Make

(** @canonical Yocaml.Markup *)
module Markup = Yocaml__Markup

(** @canonical Yocaml.Metadata *)
module Metadata = Yocaml__Metadata

(** @canonical Yocaml.Nel *)
module Nel = Yocaml__Nel

(** @canonical Yocaml.Path *)
module Path = Yocaml__Path

(** @canonical Yocaml.Pipeline *)
module Pipeline = Yocaml__Pipeline

(** @canonical Yocaml.Reader *)
module Reader = Yocaml__Reader

(** @canonical Yocaml.Required *)
module Required = Yocaml__Required

(** @canonical Yocaml.Runtime *)
module Runtime = Yocaml__Runtime

(** @canonical Yocaml.Sexp *)
module Sexp = Yocaml__Sexp

(** @canonical Yocaml.Sexp_provider *)
module Sexp_provider = Yocaml__Sexp_provider

(** @canonical Yocaml.Slug *)
module Slug = Yocaml__Slug

(** @canonical Yocaml.Task *)
module Task = Yocaml__Task

module Yocaml__ = struct end
[@@deprecated "this module is shadowed"]
