(* generated by dune *)

(** @canonical Thread_pool_cpu_affinity.Import *)
module Import = Thread_pool_cpu_affinity__Import

module Thread_pool_cpu_affinity__ = struct end
[@@deprecated "this module is shadowed"]
