(* generated by dune *)

(** @canonical Ppx_diff.Build_helper *)
module Build_helper = Ppx_diff__Build_helper

(** @canonical Ppx_diff.Builder *)
module Builder = Ppx_diff__Builder

(** @canonical Ppx_diff.Context *)
module Context = Ppx_diff__Context

(** @canonical Ppx_diff.Core_diff *)
module Core_diff = Ppx_diff__Core_diff

(** @canonical Ppx_diff.Diff *)
module Diff = Ppx_diff__Diff

(** @canonical Ppx_diff.Diff_abstract *)
module Diff_abstract = Ppx_diff__Diff_abstract

(** @canonical Ppx_diff.Diff_as_map *)
module Diff_as_map = Ppx_diff__Diff_as_map

(** @canonical Ppx_diff.Diff_as_set *)
module Diff_as_set = Ppx_diff__Diff_as_set

(** @canonical Ppx_diff.Diff_atomic *)
module Diff_atomic = Ppx_diff__Diff_atomic

(** @canonical Ppx_diff.Diff_constr *)
module Diff_constr = Ppx_diff__Diff_constr

(** @canonical Ppx_diff.Diff_core *)
module Diff_core = Ppx_diff__Diff_core

(** @canonical Ppx_diff.Diff_record *)
module Diff_record = Ppx_diff__Diff_record

(** @canonical Ppx_diff.Diff_tuple *)
module Diff_tuple = Ppx_diff__Diff_tuple

(** @canonical Ppx_diff.Diff_var *)
module Diff_var = Ppx_diff__Diff_var

(** @canonical Ppx_diff.Diff_variant *)
module Diff_variant = Ppx_diff__Diff_variant

(** @canonical Ppx_diff.Function_name *)
module Function_name = Ppx_diff__Function_name

(** @canonical Ppx_diff.How_to_diff *)
module How_to_diff = Ppx_diff__How_to_diff

(** @canonical Ppx_diff.Items *)
module Items = Ppx_diff__Items

(** @canonical Ppx_diff.Longident_helper *)
module Longident_helper = Ppx_diff__Longident_helper

(** @canonical Ppx_diff.Map_and_set_helper *)
module Map_and_set_helper = Ppx_diff__Map_and_set_helper

(** @canonical Ppx_diff.Module_name *)
module Module_name = Ppx_diff__Module_name

(** @canonical Ppx_diff.Nonempty_list *)
module Nonempty_list = Ppx_diff__Nonempty_list

(** @canonical Ppx_diff.Prefix *)
module Prefix = Ppx_diff__Prefix

(** @canonical Ppx_diff.Record_field_name *)
module Record_field_name = Ppx_diff__Record_field_name

(** @canonical Ppx_diff.Shared *)
module Shared = Ppx_diff__Shared

(** @canonical Ppx_diff.Stable_version *)
module Stable_version = Ppx_diff__Stable_version

(** @canonical Ppx_diff.Type_declaration *)
module Type_declaration = Ppx_diff__Type_declaration

(** @canonical Ppx_diff.Type_kind *)
module Type_kind = Ppx_diff__Type_kind

(** @canonical Ppx_diff.Type_name *)
module Type_name = Ppx_diff__Type_name

(** @canonical Ppx_diff.Type_param *)
module Type_param = Ppx_diff__Type_param

(** @canonical Ppx_diff.Unboxed *)
module Unboxed = Ppx_diff__Unboxed

(** @canonical Ppx_diff.Var *)
module Var = Ppx_diff__Var

(** @canonical Ppx_diff.Variant_row_name *)
module Variant_row_name = Ppx_diff__Variant_row_name

(** @canonical Ppx_diff.What_to_derive *)
module What_to_derive = Ppx_diff__What_to_derive

module Ppx_diff__ = struct end
[@@deprecated "this module is shadowed"]
