(* generated by dune *)

(** @canonical Ppx_log_kernel.Extension_kind *)
module Extension_kind = Ppx_log_kernel__Extension_kind

(** @canonical Ppx_log_kernel.Extension_payload *)
module Extension_payload = Ppx_log_kernel__Extension_payload

(** @canonical Ppx_log_kernel.Import *)
module Import = Ppx_log_kernel__Import

(** @canonical Ppx_log_kernel.Log_kind *)
module Log_kind = Ppx_log_kernel__Log_kind

(** @canonical Ppx_log_kernel.Log_statement *)
module Log_statement = Ppx_log_kernel__Log_statement

(** @canonical Ppx_log_kernel.Log_tag *)
module Log_tag = Ppx_log_kernel__Log_tag

(** @canonical Ppx_log_kernel.Message_sexp *)
module Message_sexp = Ppx_log_kernel__Message_sexp

(** @canonical Ppx_log_kernel.Optional_arg *)
module Optional_arg = Ppx_log_kernel__Optional_arg

(** @canonical Ppx_log_kernel.Parsed_extension *)
module Parsed_extension = Ppx_log_kernel__Parsed_extension

(** @canonical Ppx_log_kernel.Ppxlib_with_sexp *)
module Ppxlib_with_sexp = Ppx_log_kernel__Ppxlib_with_sexp

(** @canonical Ppx_log_kernel.Tag_data *)
module Tag_data = Ppx_log_kernel__Tag_data

module Ppx_log_kernel__ = struct end
[@@deprecated "this module is shadowed"]
