(* generated by dune *)

(** @canonical Error_checking_mutex.Import *)
module Import = Error_checking_mutex__Import

module Error_checking_mutex__ = struct end
[@@deprecated "this module is shadowed"]
