(* generated by dune *)

(** @canonical Total_map.Enumeration *)
module Enumeration = Total_map__Enumeration

(** @canonical Total_map.Enumeration_intf *)
module Enumeration_intf = Total_map__Enumeration_intf

(** @canonical Total_map.Import *)
module Import = Total_map__Import

(** @canonical Total_map.Total_map_intf *)
module Total_map_intf = Total_map__Total_map_intf

module Total_map__ = struct end
[@@deprecated "this module is shadowed"]
