(* generated by dune *)

(** @canonical Ppx_string_runtime.Ppx_string_runtime_intf *)
module Ppx_string_runtime_intf = Ppx_string_runtime__Ppx_string_runtime_intf

module Ppx_string_runtime__ = struct end
[@@deprecated "this module is shadowed"]
