(* generated by dune *)

(** @canonical Ppx_quickcheck_runtime.Quickcheckable *)
module Quickcheckable = Ppx_quickcheck_runtime__Quickcheckable

module Ppx_quickcheck_runtime__ = struct end
[@@deprecated "this module is shadowed"]
